name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Install tokenkeeper
        2. Run `tokenkeeper`
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Include error messages or stack traces if available.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "3.12.0"
    validations:
      required: true

  - type: input
    id: tokenkeeper-version
    attributes:
      label: tokenkeeper Version
      description: Output of `pip show tokenkeeper | grep Version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: ollama-version
    attributes:
      label: Ollama Version
      description: Output of `ollama --version` (if applicable)
      placeholder: "0.6.2"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Logs, screenshots, configuration, or anything else that might help.
    validations:
      required: false
