name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve? Describe the situation where this feature would be useful.
      placeholder: I want to be able to ...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should it work? Describe your ideal implementation.
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Other approaches you have thought about and why they are less ideal.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Mockups, examples, links, or anything else that helps illustrate the request.
    validations:
      required: false
